# yuncms - local development overrides

version: '2'
services:
  cli:
    volumes:
      - .:/app
    environment:
      - YII_ENV=dev
      - YII_DEBUG=1
      - DB_PORT_3306_TCP_ADDR=db
      - DB_PORT_3306_TCP_PORT=3306
      - DB_ENV_MYSQL_ROOT_USER=root
      - DB_ENV_MYSQL_ROOT_PASSWORD=secretadmin
  php:
    volumes:
      - .:/app
    environment:
      - YII_ENV=dev
      - YII_DEBUG=1
      - DB_PORT_3306_TCP_ADDR=db
      - DB_PORT_3306_TCP_PORT=3306
      - DB_ENV_MYSQL_ROOT_USER=root
      - DB_ENV_MYSQL_ROOT_PASSWORD=secretadmin
  nginx:
    ports:
      - '40080:80'
    volumes:
      - .:/app
