# yuncms - local development overrides

version: '2'
services:
  mysql:
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=yuncms_dev
  redis:
    image: redis
    restart: always
  memcached:
    image: memcached
    restart: always
  php-fpm:
    image: yuncms/php:7.1-fpm
    volumes:
      - .:/app:rw # you should uncomment this line if you want to develop the app.
    volumes_from:
      - nginx
    environment:
      - APP_ENV=Production
      - DB_PORT_3306_TCP_ADDR=db
      - DB_PORT_3306_TCP_PORT=3306
      - DB_ENV_MYSQL_ROOT_USER=root
      - DB_ENV_MYSQL_ROOT_PASSWORD=123456
    restart: always
    depends_on:
      - mysql
      - redis
      - memcached
      - nginx
  queue:
    image: yuncms/php:7.1-fpm
    volumes:
      - .:/app:rw # you should uncomment this line if you want to develop the app.
    volumes_from:
      - nginx
    environment:
      - APP_ENV=Production
      - DB_PORT_3306_TCP_ADDR=db
      - DB_PORT_3306_TCP_PORT=3306
      - DB_ENV_MYSQL_ROOT_USER=root
      - DB_ENV_MYSQL_ROOT_PASSWORD=123456
    restart: always
    command: yii queue/listen --verbose=1 --color=0
    depends_on:
      - mysql
      - redis
      - memcached
      - nginx
  nginx:
    build: .
#    volumes:
#      - .:/app:rw # you should uncomment this line if you want to develop the app.
#      - /docker/yuncms/vendor:/app/vendor:rw
#      - /docker/yuncms/composer:/root/.composer:rw
    restart: always
    ports:
      - '40080:80'
