<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2017-09-27 16:45:15
 */
return [
    'vendor' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'vendor-f9640284b5df06e22ce0dbf0d93cb75f.js',
        ],
        'css' => [
            'vendor-99639e6d722a94564734f5732a35f328.css',
        ],
        'sourcePath' => null,
        'depends' => [],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [
            '//cdn.bootcss.com/jquery/2.2.4/jquery.min.js',
        ],
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'yii\\web\\JqueryAsset',
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'vendor',
        ],
    ],
    'yii\\captcha\\CaptchaAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'vendor',
        ],
    ],
    'yii\\validators\\ValidationAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'vendor',
        ],
    ],
    'yii\\widgets\\ActiveFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'vendor',
        ],
    ],
    'yii\\grid\\GridViewAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'vendor',
        ],
    ],
    'xutl\\fmt\\Asset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'vendor',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'css' => [
            '//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css',
        ],
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'js' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'yii\\bootstrap\\BootstrapAsset',
    ],
    'yii\\bootstrap\\BootstrapPluginAsset' => [
        'sourcePath' => null,
        'js' => [
            '//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js',
        ],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap\\BootstrapAsset',
        ],
        'basePath' => null,
        'baseUrl' => null,
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'yii\\bootstrap\\BootstrapPluginAsset',
    ],
    'xutl\\cropper\\CropperAsset' => [
        'sourcePath' => null,
        'css' => [
            '//cdn.bootcss.com/cropper/2.3.4/cropper.min.css',
        ],
        'js' => [
            '//cdn.bootcss.com/cropper/2.3.4/cropper.min.js',
        ],
        'depends' => [
            'yii\\bootstrap\\BootstrapAsset',
            'yii\\bootstrap\\BootstrapPluginAsset',
        ],
        'basePath' => null,
        'baseUrl' => null,
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'xutl\\cropper\\CropperAsset',
    ],
    'yuncms\\user\\frontend\\assets\\CropperAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'xutl\\cropper\\CropperAsset',
            'vendor',
        ],
    ],
    'xutl\\fontawesome\\Asset' => [
        'sourcePath' => null,
        'css' => [
            '//cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css',
        ],
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'js' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [
            'beforeCopy' => function ($from, $to) {

            return preg_match('%(/|\\\\)(fonts|css)%', $from);

        },
        ],
        'class' => 'xutl\\fontawesome\\Asset',
    ],
    'frontend\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'yii\\bootstrap\\BootstrapPluginAsset',
            'xutl\\fmt\\Asset',
            'xutl\\fontawesome\\Asset',
            'vendor',
        ],
    ],
    'yii\\widgets\\MaskedInputAsset' => [
        'sourcePath' => null,
        'js' => [
            '//cdn.bootcss.com/jquery.inputmask/3.3.4/jquery.inputmask.bundle.min.js',
        ],
        'depends' => [
            'yii\\web\\YiiAsset',
        ],
        'basePath' => null,
        'baseUrl' => null,
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'yii\\widgets\\MaskedInputAsset',
    ],
    'yii\\jui\\JuiAsset' => [
        'sourcePath' => null,
        'js' => [
            '//cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.min.js',
        ],
        'css' => [
            '//cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.min.css',
        ],
        'depends' => [
            'yii\\web\\JqueryAsset',
        ],
        'basePath' => null,
        'baseUrl' => null,
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'yii\\jui\\JuiAsset',
    ],
    'xutl\\bootstrap\\filestyle\\FilestyleAsset' => [
        'sourcePath' => null,
        'js' => [
            '//cdn.bootcss.com/bootstrap-filestyle/1.3.0/bootstrap-filestyle.min.js',
        ],
        'depends' => [
            'yii\\bootstrap\\BootstrapPluginAsset',
        ],
        'basePath' => null,
        'baseUrl' => null,
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'xutl\\bootstrap\\filestyle\\FilestyleAsset',
    ],
];