<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '关于',
    'Articles' => '',
    'Contact' => '',
    'English (US)' => '',
    'GitHub' => '',
    'Home' => '主页',
    'Language' => '',
    'Next page' => '下一页',
    'No introduction' => '',
    'Notes' => '笔记',
    'Previous page' => '',
    'Privacy' => '',
    'Questions' => '问答',
    'Sign In' => '',
    'Sign Up' => '',
    'Topic' => '话题',
    'Topics' => '话题',
    'Topics can not only organize and categorize your content, but also link similar content. Correct use of the topic will make your problem more people find and solve.' => '',
    'follows' => '',
    '简体中文' => '',
];
