mysql:
  image: mysql
  environment:
    - MYSQL_DATABASE=yuncms
    - MYSQL_ROOT_PASSWORD=123456
  ports:
    - 3306:3306

web:
  build: .
  links:
    - mysql:mysql
  ports:
    - 80:80
  environment:
    - MYSQL_INSTANCE_NAME=yuncms
    - MYSQL_PASSWORD=123456
    - APP_ENV=Production
  volumes:
    - ./vendor:/app/vendor:rw
    - ~/.composer/cache:/root/.composer/cache:rw
    # - .:/app:rw # you should uncomment this line if you want to develop the app.
